export interface ExerciseItem {
    id: string;
    name: string;
    category: string;
    muscleGroup: string;
}

export default class ExerciseLibraryCON {
    public static readonly EXERCISES: ExerciseItem[] = [
        // ─── Chest ────────────────────────────────────────────────────
        {
            id: "barbell-bench-press",
            name: "Bench Press",
            category: "Barbell",
            muscleGroup: "Chest",
        },
        {
            id: "incline-barbell-bench-press",
            name: "Incline Bench Press",
            category: "Barbell",
            muscleGroup: "Chest",
        },
        {
            id: "decline-barbell-bench-press",
            name: "Decline Bench Press",
            category: "Barbell",
            muscleGroup: "Chest",
        },
        {
            id: "guillotine-press",
            name: "Guillotine Press",
            category: "Barbell",
            muscleGroup: "Chest",
        },
        {
            id: "floor-press",
            name: "Floor Press",
            category: "Barbell",
            muscleGroup: "Chest",
        },
        {
            id: "reverse-grip-bench-press",
            name: "Reverse Grip Bench Press",
            category: "Barbell",
            muscleGroup: "Chest",
        },
        {
            id: "dumbbell-bench-press",
            name: "Dumbbell Bench Press",
            category: "Dumbbell",
            muscleGroup: "Chest",
        },
        {
            id: "incline-dumbbell-press",
            name: "Incline Dumbbell Press",
            category: "Dumbbell",
            muscleGroup: "Chest",
        },
        {
            id: "decline-dumbbell-press",
            name: "Decline Dumbbell Press",
            category: "Dumbbell",
            muscleGroup: "Chest",
        },
        {
            id: "dumbbell-fly",
            name: "Dumbbell Fly",
            category: "Dumbbell",
            muscleGroup: "Chest",
        },
        {
            id: "incline-dumbbell-fly",
            name: "Incline Dumbbell Fly",
            category: "Dumbbell",
            muscleGroup: "Chest",
        },
        {
            id: "decline-dumbbell-fly",
            name: "Decline Dumbbell Fly",
            category: "Dumbbell",
            muscleGroup: "Chest",
        },
        {
            id: "dumbbell-pullover",
            name: "Dumbbell Pullover",
            category: "Dumbbell",
            muscleGroup: "Chest",
        },
        {
            id: "dumbbell-squeeze-press",
            name: "Dumbbell Squeeze Press",
            category: "Dumbbell",
            muscleGroup: "Chest",
        },
        {
            id: "hex-press",
            name: "Hex Press",
            category: "Dumbbell",
            muscleGroup: "Chest",
        },
        {
            id: "chest-press-machine",
            name: "Chest Press Machine",
            category: "Machine",
            muscleGroup: "Chest",
        },
        {
            id: "incline-chest-press-machine",
            name: "Incline Chest Press Machine",
            category: "Machine",
            muscleGroup: "Chest",
        },
        {
            id: "pec-deck-fly",
            name: "Pec Deck Fly",
            category: "Machine",
            muscleGroup: "Chest",
        },
        {
            id: "incline-fly-machine",
            name: "Incline Fly Machine",
            category: "Machine",
            muscleGroup: "Chest",
        },
        {
            id: "plate-loaded-chest-press",
            name: "Plate Loaded Chest Press",
            category: "Machine",
            muscleGroup: "Chest",
        },
        {
            id: "cable-fly",
            name: "Cable Fly",
            category: "Cable",
            muscleGroup: "Chest",
        },
        {
            id: "low-to-high-cable-fly",
            name: "Low-to-High Cable Fly",
            category: "Cable",
            muscleGroup: "Chest",
        },
        {
            id: "high-to-low-cable-fly",
            name: "High-to-Low Cable Fly",
            category: "Cable",
            muscleGroup: "Chest",
        },
        {
            id: "standing-cable-press",
            name: "Standing Cable Press",
            category: "Cable",
            muscleGroup: "Chest",
        },
        {
            id: "single-arm-cable-press",
            name: "Single Arm Cable Press",
            category: "Cable",
            muscleGroup: "Chest",
        },
        {
            id: "cable-pullover",
            name: "Cable Pullover",
            category: "Cable",
            muscleGroup: "Chest",
        },
        {
            id: "push-up",
            name: "Push-up",
            category: "Bodyweight",
            muscleGroup: "Chest",
        },
        {
            id: "wide-push-up",
            name: "Wide Push-up",
            category: "Bodyweight",
            muscleGroup: "Chest",
        },
        {
            id: "diamond-push-up",
            name: "Diamond Push-up",
            category: "Bodyweight",
            muscleGroup: "Chest",
        },
        {
            id: "archer-push-up",
            name: "Archer Push-up",
            category: "Bodyweight",
            muscleGroup: "Chest",
        },
        {
            id: "decline-push-up",
            name: "Decline Push-up",
            category: "Bodyweight",
            muscleGroup: "Chest",
        },
        {
            id: "incline-push-up",
            name: "Incline Push-up",
            category: "Bodyweight",
            muscleGroup: "Chest",
        },
        {
            id: "ring-push-up",
            name: "Ring Push-up",
            category: "Bodyweight",
            muscleGroup: "Chest",
        },
        {
            id: "clap-push-up",
            name: "Clap Push-up",
            category: "Bodyweight",
            muscleGroup: "Chest",
        },
        {
            id: "plyometric-push-up",
            name: "Plyometric Push-up",
            category: "Bodyweight",
            muscleGroup: "Chest",
        },
        {
            id: "one-arm-push-up",
            name: "One Arm Push-up",
            category: "Bodyweight",
            muscleGroup: "Chest",
        },

        // ─── Back ─────────────────────────────────────────────────────
        {
            id: "deadlift",
            name: "Deadlift",
            category: "Barbell",
            muscleGroup: "Back",
        },
        {
            id: "sumo-deadlift",
            name: "Sumo Deadlift",
            category: "Barbell",
            muscleGroup: "Back",
        },
        {
            id: "rack-pull",
            name: "Rack Pull",
            category: "Barbell",
            muscleGroup: "Back",
        },
        {
            id: "barbell-row",
            name: "Barbell Row",
            category: "Barbell",
            muscleGroup: "Back",
        },
        {
            id: "yates-row",
            name: "Yates Row",
            category: "Barbell",
            muscleGroup: "Back",
        },
        {
            id: "pendlay-row",
            name: "Pendlay Row",
            category: "Barbell",
            muscleGroup: "Back",
        },
        {
            id: "t-bar-row",
            name: "T-Bar Row",
            category: "Barbell",
            muscleGroup: "Back",
        },
        {
            id: "dumbbell-row",
            name: "Dumbbell Row",
            category: "Dumbbell",
            muscleGroup: "Back",
        },
        {
            id: "chest-supported-dumbbell-row",
            name: "Chest Supported Dumbbell Row",
            category: "Dumbbell",
            muscleGroup: "Back",
        },
        {
            id: "incline-dumbbell-row",
            name: "Incline Dumbbell Row",
            category: "Dumbbell",
            muscleGroup: "Back",
        },
        {
            id: "dumbbell-shrug",
            name: "Dumbbell Shrug",
            category: "Dumbbell",
            muscleGroup: "Back",
        },
        {
            id: "barbell-shrug",
            name: "Barbell Shrug",
            category: "Barbell",
            muscleGroup: "Back",
        },
        {
            id: "renegade-row",
            name: "Renegade Row",
            category: "Dumbbell",
            muscleGroup: "Back",
        },
        {
            id: "lat-pulldown-machine",
            name: "Lat Pulldown Machine",
            category: "Machine",
            muscleGroup: "Back",
        },
        {
            id: "assisted-pull-up-machine",
            name: "Assisted Pull-up Machine",
            category: "Machine",
            muscleGroup: "Back",
        },
        {
            id: "back-extension-machine",
            name: "Back Extension Machine",
            category: "Machine",
            muscleGroup: "Back",
        },
        {
            id: "chest-supported-row-machine",
            name: "Chest-Supported Row Machine",
            category: "Machine",
            muscleGroup: "Back",
        },
        {
            id: "seated-cable-row",
            name: "Seated Cable Row",
            category: "Cable",
            muscleGroup: "Back",
        },
        {
            id: "straight-arm-cable-pullover",
            name: "Straight Arm Cable Pullover",
            category: "Cable",
            muscleGroup: "Back",
        },
        {
            id: "single-arm-cable-row",
            name: "Single Arm Cable Row",
            category: "Cable",
            muscleGroup: "Back",
        },
        {
            id: "pull-up",
            name: "Pull-up",
            category: "Bodyweight",
            muscleGroup: "Back",
        },
        {
            id: "chin-up",
            name: "Chin-up",
            category: "Bodyweight",
            muscleGroup: "Back",
        },
        {
            id: "wide-grip-pull-up",
            name: "Wide Grip Pull-up",
            category: "Bodyweight",
            muscleGroup: "Back",
        },
        {
            id: "inverted-row",
            name: "Inverted Row",
            category: "Bodyweight",
            muscleGroup: "Back",
        },
        {
            id: "muscle-up",
            name: "Muscle-up",
            category: "Bodyweight",
            muscleGroup: "Back",
        },

        // ─── Shoulders ────────────────────────────────────────────────
        {
            id: "overhead-press",
            name: "Overhead Press",
            category: "Barbell",
            muscleGroup: "Shoulders",
        },
        {
            id: "push-press",
            name: "Push Press",
            category: "Barbell",
            muscleGroup: "Shoulders",
        },
        {
            id: "behind-the-neck-press",
            name: "Behind the Neck Press",
            category: "Barbell",
            muscleGroup: "Shoulders",
        },
        {
            id: "barbell-front-raise",
            name: "Barbell Front Raise",
            category: "Barbell",
            muscleGroup: "Shoulders",
        },
        {
            id: "upright-row",
            name: "Upright Row",
            category: "Barbell",
            muscleGroup: "Shoulders",
        },
        {
            id: "dumbbell-shoulder-press",
            name: "Dumbbell Shoulder Press",
            category: "Dumbbell",
            muscleGroup: "Shoulders",
        },
        {
            id: "arnold-press",
            name: "Arnold Press",
            category: "Dumbbell",
            muscleGroup: "Shoulders",
        },
        {
            id: "dumbbell-lateral-raise",
            name: "Dumbbell Lateral Raise",
            category: "Dumbbell",
            muscleGroup: "Shoulders",
        },
        {
            id: "dumbbell-front-raise",
            name: "Dumbbell Front Raise",
            category: "Dumbbell",
            muscleGroup: "Shoulders",
        },
        {
            id: "dumbbell-rear-delt-fly",
            name: "Dumbbell Rear Delt Fly",
            category: "Dumbbell",
            muscleGroup: "Shoulders",
        },
        {
            id: "shoulder-press-machine",
            name: "Shoulder Press Machine",
            category: "Machine",
            muscleGroup: "Shoulders",
        },
        {
            id: "lateral-raise-machine",
            name: "Lateral Raise Machine",
            category: "Machine",
            muscleGroup: "Shoulders",
        },
        {
            id: "reverse-pec-deck",
            name: "Reverse Pec Deck",
            category: "Machine",
            muscleGroup: "Shoulders",
        },
        {
            id: "smith-machine-shoulder-press",
            name: "Smith Machine Shoulder Press",
            category: "Machine",
            muscleGroup: "Shoulders",
        },
        {
            id: "cable-lateral-raise",
            name: "Cable Lateral Raise",
            category: "Cable",
            muscleGroup: "Shoulders",
        },
        {
            id: "cable-front-raise",
            name: "Cable Front Raise",
            category: "Cable",
            muscleGroup: "Shoulders",
        },
        {
            id: "cable-face-pull",
            name: "Cable Face Pull",
            category: "Cable",
            muscleGroup: "Shoulders",
        },
        {
            id: "cable-rear-delt-fly",
            name: "Cable Rear Delt Fly",
            category: "Cable",
            muscleGroup: "Shoulders",
        },
        {
            id: "handstand-push-up",
            name: "Handstand Push-up",
            category: "Bodyweight",
            muscleGroup: "Shoulders",
        },
        {
            id: "pike-push-up",
            name: "Pike Push-up",
            category: "Bodyweight",
            muscleGroup: "Shoulders",
        },

        // ─── Biceps ───────────────────────────────────────────────────
        {
            id: "barbell-curl",
            name: "Barbell Curl",
            category: "Barbell",
            muscleGroup: "Biceps",
        },
        {
            id: "ez-bar-curl",
            name: "EZ Bar Curl",
            category: "Barbell",
            muscleGroup: "Biceps",
        },
        {
            id: "spider-curl",
            name: "Spider Curl",
            category: "Barbell",
            muscleGroup: "Biceps",
        },
        {
            id: "drag-curl",
            name: "Drag Curl",
            category: "Barbell",
            muscleGroup: "Biceps",
        },
        {
            id: "dumbbell-curl",
            name: "Dumbbell Curl",
            category: "Dumbbell",
            muscleGroup: "Biceps",
        },
        {
            id: "incline-dumbbell-curl",
            name: "Incline Dumbbell Curl",
            category: "Dumbbell",
            muscleGroup: "Biceps",
        },
        {
            id: "hammer-curl",
            name: "Hammer Curl",
            category: "Dumbbell",
            muscleGroup: "Biceps",
        },
        {
            id: "concentration-curl",
            name: "Concentration Curl",
            category: "Dumbbell",
            muscleGroup: "Biceps",
        },
        {
            id: "preacher-curl",
            name: "Preacher Curl",
            category: "Dumbbell",
            muscleGroup: "Biceps",
        },
        {
            id: "zottman-curl",
            name: "Zottman Curl",
            category: "Dumbbell",
            muscleGroup: "Biceps",
        },
        {
            id: "preacher-curl-machine",
            name: "Preacher Curl Machine",
            category: "Machine",
            muscleGroup: "Biceps",
        },
        {
            id: "bicep-curl-machine",
            name: "Bicep Curl Machine",
            category: "Machine",
            muscleGroup: "Biceps",
        },
        {
            id: "cable-bicep-curl",
            name: "Cable Bicep Curl",
            category: "Cable",
            muscleGroup: "Biceps",
        },
        {
            id: "cable-hammer-curl",
            name: "Cable Hammer Curl",
            category: "Cable",
            muscleGroup: "Biceps",
        },
        {
            id: "hercules-curl",
            name: "Hercules Curl",
            category: "Cable",
            muscleGroup: "Biceps",
        },

        // ─── Triceps ──────────────────────────────────────────────────
        {
            id: "close-grip-bench-press",
            name: "Close Grip Bench Press",
            category: "Barbell",
            muscleGroup: "Triceps",
        },
        {
            id: "skull-crusher",
            name: "Skull Crusher",
            category: "Barbell",
            muscleGroup: "Triceps",
        },
        {
            id: "jm-press",
            name: "JM Press",
            category: "Barbell",
            muscleGroup: "Triceps",
        },
        {
            id: "dumbbell-overhead-triceps-extension",
            name: "Dumbbell Overhead Triceps Extension",
            category: "Dumbbell",
            muscleGroup: "Triceps",
        },
        {
            id: "dumbbell-kickback",
            name: "Dumbbell Kickback",
            category: "Dumbbell",
            muscleGroup: "Triceps",
        },
        {
            id: "dumbbell-skull-crusher",
            name: "Dumbbell Skull Crusher",
            category: "Dumbbell",
            muscleGroup: "Triceps",
        },
        {
            id: "tate-press",
            name: "Tate Press",
            category: "Dumbbell",
            muscleGroup: "Triceps",
        },
        {
            id: "triceps-dip-machine",
            name: "Triceps Dip Machine",
            category: "Machine",
            muscleGroup: "Triceps",
        },
        {
            id: "triceps-pushdown-machine",
            name: "Triceps Pushdown Machine",
            category: "Machine",
            muscleGroup: "Triceps",
        },
        {
            id: "cable-triceps-pushdown",
            name: "Cable Triceps Pushdown",
            category: "Cable",
            muscleGroup: "Triceps",
        },
        {
            id: "cable-overhead-triceps-extension",
            name: "Cable Overhead Triceps Extension",
            category: "Cable",
            muscleGroup: "Triceps",
        },
        {
            id: "single-arm-cable-pushdown",
            name: "Single Arm Cable Pushdown",
            category: "Cable",
            muscleGroup: "Triceps",
        },
        {
            id: "parallel-bar-dips",
            name: "Parallel Bar Dips",
            category: "Bodyweight",
            muscleGroup: "Triceps",
        },
        {
            id: "bench-dips",
            name: "Bench Dips",
            category: "Bodyweight",
            muscleGroup: "Triceps",
        },

        // ─── Legs ─────────────────────────────────────────────────────
        {
            id: "back-squat",
            name: "Back Squat",
            category: "Barbell",
            muscleGroup: "Legs",
        },
        {
            id: "front-squat",
            name: "Front Squat",
            category: "Barbell",
            muscleGroup: "Legs",
        },
        {
            id: "romanian-deadlift",
            name: "Romanian Deadlift",
            category: "Barbell",
            muscleGroup: "Legs",
        },
        {
            id: "stiff-legged-deadlift",
            name: "Stiff-Legged Deadlift",
            category: "Barbell",
            muscleGroup: "Legs",
        },
        {
            id: "barbell-hip-thrust",
            name: "Barbell Hip Thrust",
            category: "Barbell",
            muscleGroup: "Legs",
        },
        {
            id: "barbell-good-morning",
            name: "Barbell Good Morning",
            category: "Barbell",
            muscleGroup: "Legs",
        },
        {
            id: "dumbbell-romanian-deadlift",
            name: "Dumbbell Romanian Deadlift",
            category: "Dumbbell",
            muscleGroup: "Legs",
        },
        {
            id: "dumbbell-goblet-squat",
            name: "Dumbbell Goblet Squat",
            category: "Dumbbell",
            muscleGroup: "Legs",
        },
        {
            id: "dumbbell-lunge",
            name: "Dumbbell Lunge",
            category: "Dumbbell",
            muscleGroup: "Legs",
        },
        {
            id: "dumbbell-bulgarian-split-squat",
            name: "Dumbbell Bulgarian Split Squat",
            category: "Dumbbell",
            muscleGroup: "Legs",
        },
        {
            id: "dumbbell-step-up",
            name: "Dumbbell Step-up",
            category: "Dumbbell",
            muscleGroup: "Legs",
        },
        {
            id: "leg-press",
            name: "Leg Press",
            category: "Machine",
            muscleGroup: "Legs",
        },
        {
            id: "hack-squat-machine",
            name: "Hack Squat Machine",
            category: "Machine",
            muscleGroup: "Legs",
        },
        {
            id: "leg-extension-machine",
            name: "Leg Extension Machine",
            category: "Machine",
            muscleGroup: "Legs",
        },
        {
            id: "lying-leg-curl-machine",
            name: "Lying Leg Curl Machine",
            category: "Machine",
            muscleGroup: "Legs",
        },
        {
            id: "seated-leg-curl-machine",
            name: "Seated Leg Curl Machine",
            category: "Machine",
            muscleGroup: "Legs",
        },
        {
            id: "smith-machine-squat",
            name: "Smith Machine Squat",
            category: "Machine",
            muscleGroup: "Legs",
        },
        {
            id: "cable-pull-through",
            name: "Cable Pull-through",
            category: "Cable",
            muscleGroup: "Legs",
        },
        {
            id: "cable-glute-kickback",
            name: "Cable Glute Kickback",
            category: "Cable",
            muscleGroup: "Legs",
        },
        {
            id: "pistol-squat",
            name: "Pistol Squat",
            category: "Bodyweight",
            muscleGroup: "Legs",
        },
        {
            id: "nordic-hamstring-curl",
            name: "Nordic Hamstring Curl",
            category: "Bodyweight",
            muscleGroup: "Legs",
        },

        // ─── Calves ───────────────────────────────────────────────────
        {
            id: "barbell-calf-raise",
            name: "Barbell Calf Raise",
            category: "Barbell",
            muscleGroup: "Calves",
        },
        {
            id: "dumbbell-calf-raise",
            name: "Dumbbell Calf Raise",
            category: "Dumbbell",
            muscleGroup: "Calves",
        },
        {
            id: "standing-calf-raise-machine",
            name: "Standing Calf Raise Machine",
            category: "Machine",
            muscleGroup: "Calves",
        },
        {
            id: "seated-calf-raise-machine",
            name: "Seated Calf Raise Machine",
            category: "Machine",
            muscleGroup: "Calves",
        },
        {
            id: "leg-press-calf-press",
            name: "Leg Press Calf Press",
            category: "Machine",
            muscleGroup: "Calves",
        },
        {
            id: "standing-bodyweight-calf-raise",
            name: "Standing Bodyweight Calf Raise",
            category: "Bodyweight",
            muscleGroup: "Calves",
        },

        // ─── Core ─────────────────────────────────────────────────────
        {
            id: "barbell-rollout",
            name: "Barbell Rollout",
            category: "Barbell",
            muscleGroup: "Core",
        },
        {
            id: "dumbbell-side-bend",
            name: "Dumbbell Side Bend",
            category: "Dumbbell",
            muscleGroup: "Core",
        },
        {
            id: "cable-crunch",
            name: "Cable Crunch",
            category: "Cable",
            muscleGroup: "Core",
        },
        {
            id: "cable-woodchopper",
            name: "Cable Woodchopper",
            category: "Cable",
            muscleGroup: "Core",
        },
        {
            id: "hanging-leg-raise",
            name: "Hanging Leg Raise",
            category: "Bodyweight",
            muscleGroup: "Core",
        },
        {
            id: "plank",
            name: "Plank",
            category: "Bodyweight",
            muscleGroup: "Core",
        },
        {
            id: "bicycle-crunch",
            name: "Bicycle Crunch",
            category: "Bodyweight",
            muscleGroup: "Core",
        },
        {
            id: "ab-wheel-rollout",
            name: "Ab Wheel Rollout",
            category: "Bodyweight",
            muscleGroup: "Core",
        },
    ];
}
